[project]
name = "matrix-lab-nodes"
version = "0.3.2"
description = "MATRIX LAB custom nodes for ComfyUI."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "MATRIX LAB" }]
dependencies = ["Pillow", "aiohttp", "numpy", "scipy", "torch"]

[project.urls]
Repository = "https://github.com/JsonMatrixLab/MATRIX-LAB-Nodes"
